# Numpy

In [23]:
import numpy as np

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [24]:
arr = np.linspace(0, 20, 4 * 7).reshape(4, 7)
(arr - np.min(arr)) / (np.max(arr) - np.min(arr))

array([[0.        , 0.03703704, 0.07407407, 0.11111111, 0.14814815,
        0.18518519, 0.22222222],
       [0.25925926, 0.2962963 , 0.33333333, 0.37037037, 0.40740741,
        0.44444444, 0.48148148],
       [0.51851852, 0.55555556, 0.59259259, 0.62962963, 0.66666667,
        0.7037037 , 0.74074074],
       [0.77777778, 0.81481481, 0.85185185, 0.88888889, 0.92592593,
        0.96296296, 1.        ]])

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [25]:
arr = np.random.randint(0, 11, (8, 10))
ind = np.argmin(np.sum(arr, axis=1))
print(f"Индекс {ind}")
print(f"Строка {arr[ind]}")

Индекс 6
Строка [ 1  1  8  4  6 10  2  0  0  5]


3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [26]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
np.sqrt(np.sum(np.square(arr1 - arr2)))

5.196152422706632

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [27]:
A = np.array([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]])
B = np.array([[3, -1], [2, 1]])
C = np.array([[7, 21], [11, 8], [8, 4]])
X = np.dot(np.dot(np.linalg.inv(A), -C), np.linalg.inv(B))
X

array([[ 1.00000000e+00,  5.55111512e-16],
       [-2.00000000e+00,  1.00000000e+00],
       [ 3.00000000e+00, -4.00000000e+00]])

## Лабораторная работа №1


Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [28]:
data = np.loadtxt("minutes_n_ingredients.csv", dtype=np.int32, delimiter=',', skiprows=1)
print(data[:5])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [29]:
print(np.average(data[:, 1:], axis=0))
print(np.min(data[:, 1:], axis=0))
print(np.max(data[:, 1:], axis=0))
print(np.median(data[:, 1:], axis=0))

[2.16010017e+04 9.05528000e+00]
[0 1]
[2147483647         39]
[40.  9.]


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [30]:
data[:, 1] = np.clip(data[:, 1], np.min(data[:, 1]), np.quantile(data[:, 1], 0.75))
data

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       ...,
       [498432,     65,     15],
       [370915,      5,      4],
       [ 81993,     65,     14]])

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [31]:
x = np.where(data[:, 1] == 0)
print(x[0].size)
data[x, 1] = 1

479


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [32]:
np.unique(data[:, 0]).size

100000

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [33]:
x = np.unique(data[:, 2])
print(x.size)
print(x)

37
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 37 39]


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [34]:
data2 = data[data[:, 2] <= 5]
data2

array([[446597,     15,      5],
       [204134,      5,      3],
       [ 25623,      6,      4],
       ...,
       [ 52088,     60,      5],
       [128811,     15,      4],
       [370915,      5,      4]])

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [35]:
ing_on_time = data[:, 2] / data[:, 1]
max(ing_on_time)

24.0

9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [36]:
np.average(data[np.argsort(data[:, 1])[::-1][:100]][:, 2])

9.96

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [37]:
data[np.random.choice(data.shape[0], size=10)]

array([[306776,     20,      5],
       [  7001,     24,      6],
       [172420,     65,      8],
       [ 43663,     65,      7],
       [ 28397,     65,     10],
       [503822,     25,      4],
       [394904,     65,      9],
       [149514,      2,      2],
       [101488,     65,     10],
       [328256,     30,     12]])

11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [38]:
print(f"{data[data[:, 2] < np.average(data[:, 2])].shape[0] / data.shape[0] * 100}%")

58.802%


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [39]:
cp = data.copy()
np.hstack((cp, np.logical_and(cp[:, 1] <= 20, cp[:, 2] <= 5).astype(int)[:, None]))

array([[127244,     60,     16,      0],
       [ 23891,     25,      7,      0],
       [ 94746,     10,      6,      0],
       ...,
       [498432,     65,     15,      0],
       [370915,      5,      4,      1],
       [ 81993,     65,     14,      0]])

13. Выведите процент "простых" рецептов в датасете

In [40]:
print(f"{data[np.logical_and(data[:, 1] <= 20, data[:, 2] <= 5)].shape[0] / data.shape[0] * 100}%")

9.552%


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [41]:
f = data[data[:, 1] < 10]
s = data[np.logical_and(data[:, 1] >= 10, data[:, 1] < 20)]
t = data[data[:, 1] >= 20]
min_size = min(f.shape[0], s.shape[0], t.shape[0])
f = f[:min_size, :]
s = s[:min_size, :]
t = t[:min_size, :]
ans = np.array([f, s, t])
ans.shape

(3, 7588, 3)